export enum ConfigKeys {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  NODE_ENV = 'NODE_ENV',
  GITHUB_TOKEN = 'GITHUB_TOKEN',
  GITHUB_REPOS = 'GITHUB_REPOS',
  GOOGLE_ANALYTICS_IDS = 'GOOGLE_ANALYTICS_IDS',
}
